from typing import Any

class Message:
    message: Any = ...
    attributes: Any = ...
    data: Any = ...
    def __init__(self, message: Any) -> None: ...
    def __getattr__(self, attr: Any) -> Any: ...
