from collections import namedtuple
from fluidly.pubsub.message import Message as Message
from typing import Any

def mock_message(payload: str, attributes: dict=...) -> Any: ...
def message_from_dict(payload_dict: dict, attributes: dict=...) -> Any: ...
def message_from_tuple(payload_tuple: namedtuple, attributes: dict=...) -> Any: ...
