version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: yamllint
    versions:
    - 1.26.0
  - dependency-name: pre-commit
    versions:
    - 2.10.0
