---
# See https://developer.github.com/v3/repos/#edit for all available settings.

_extends: .github:.github/default-settings.yml

repository:
  name: python-shared
  description: One repo to share them all 🔥

collaborators:
  - username: fluidly-machine
    permission: pull


branches:
  - name: master
    protection:
      required_status_checks:
        contexts:
          - "ci/circleci: test"
          - "ci/circleci: check_version_numbers"
