---
# See https://developer.github.com/v3/repos/#edit for all available settings.

_extends: .github:.github/default-settings.yml

repository:
  name: python-shared
  description: One repo to share them all 🔥
  private: false

collaborators:
  - username: fluidly-machine
    permission: pull


branches:
  - name: master
    protection:
      required_status_checks:
        contexts:
          - "ci/circleci: check_version_numbers"
          - "ci/circleci: format_check"
          - "ci/circleci: lint"
          - "ci/circleci: type_check-3.7"
          - "ci/circleci: type_check-3.8"
          - "ci/circleci: type_check-3.9"
          - "ci/circleci: type_check-3.10"
          - "ci/circleci: test-3.7"
          - "ci/circleci: test-3.8"
          - "ci/circleci: test-3.9"
