from typing import Any, Optional

class APIException(Exception):
    title: Any = ...
    status: Any = ...
    detail: Any = ...
    def __init__(
        self, status: Any, title: Any, detail: Optional[Any] = ...
    ) -> None: ...
    def to_dict(self): ...

def handle_api_exception(error: Any): ...
