---
version: 2.1

jobs:
  test:
    resource_class: small
    working_directory: ~/app/src
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip install nox
      - run:
          name: Run format-check
          command: nox -s format_check
      - run:
          name: Run lint
          command: nox -s lint
      - run:
          name: Run type-check
          command: nox -s type_check
      - run:
          name: Run pytest
          command: nox -s pytest

workflows:
  "Test":
    jobs:
      - test:
          context: PUBLISHING
