---
version: 2.1

jobs:
  check_version_numbers:
    resource_class: small
    working_directory: ~/app/src
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          command: ./scripts/check_versions_bumped.sh

  format_check:
    resource_class: small
    working_directory: ~/app/src
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          command: pip install nox
      - run:
          name: Run format-check
          command: nox -s format_check

  lint:
    resource_class: small
    working_directory: ~/app/src
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          command: pip install nox
      - run:
          name: Run lint
          command: nox -s lint

  test:
    resource_class: small
    working_directory: ~/app/src
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          command: pip install nox
      - run:
          name: Run lint
          command: nox -s lint
      - run:
          name: Run type-check
          command: nox -s type_check
      - run:
          name: Run pytest
          command: nox -s test

  publish:
    resource_class: small
    working_directory: ~/app/src
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pipenv install --dev
      - run:
          command: ./scripts/publish_to_pypi.sh

workflows:
  "Check version numbers":
    jobs:
      - check_version_numbers:
          filters:
            branches:
              ignore: master

  "Test":
    jobs:
      - format_check:
          filters:
            branches:
              ignore: master
      - lint:
          filters:
            branches:
              ignore: master
      - test:
          filters:
            branches:
              ignore: master

  "Publish to PyPi":
    jobs:
      - publish:
          context: PYPI_PUBLISHING
          filters:
            branches:
              only: master
