from collections import namedtuple
from typing import Any

from fluidly.pubsub.message import Message as Message

def mock_message(payload: str, attributes: dict = ...) -> Any: ...
def message_from_dict(payload_dict: dict, attributes: dict = ...) -> Any: ...
def message_from_tuple(payload_tuple: namedtuple, attributes: dict = ...) -> Any: ...
